package ru.yugsys.vvvresearch.lconfig.model.DataBaseClasses;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import ru.yugsys.vvvresearch.lconfig.model.DataEntity.MainDevice;
import ru.yugsys.vvvresearch.lconfig.model.DataEntity.Device;

import ru.yugsys.vvvresearch.lconfig.model.DataBaseClasses.MainDeviceDao;
import ru.yugsys.vvvresearch.lconfig.model.DataBaseClasses.DeviceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mainDeviceDaoConfig;
    private final DaoConfig deviceDaoConfig;

    private final MainDeviceDao mainDeviceDao;
    private final DeviceDao deviceDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mainDeviceDaoConfig = daoConfigMap.get(MainDeviceDao.class).clone();
        mainDeviceDaoConfig.initIdentityScope(type);

        deviceDaoConfig = daoConfigMap.get(DeviceDao.class).clone();
        deviceDaoConfig.initIdentityScope(type);

        mainDeviceDao = new MainDeviceDao(mainDeviceDaoConfig, this);
        deviceDao = new DeviceDao(deviceDaoConfig, this);

        registerDao(MainDevice.class, mainDeviceDao);
        registerDao(Device.class, deviceDao);
    }
    
    public void clear() {
        mainDeviceDaoConfig.clearIdentityScope();
        deviceDaoConfig.clearIdentityScope();
    }

    public MainDeviceDao getMainDeviceDao() {
        return mainDeviceDao;
    }

    public DeviceDao getDeviceDao() {
        return deviceDao;
    }

}
