package ru.yugsys.vvvresearch.lconfig.model.DataBaseClasses;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import ru.yugsys.vvvresearch.lconfig.model.DataEntity.Device;
import ru.yugsys.vvvresearch.lconfig.model.DataEntity.MDevice;

import ru.yugsys.vvvresearch.lconfig.model.DataBaseClasses.DeviceDao;
import ru.yugsys.vvvresearch.lconfig.model.DataBaseClasses.MDeviceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig deviceDaoConfig;
    private final DaoConfig mDeviceDaoConfig;

    private final DeviceDao deviceDao;
    private final MDeviceDao mDeviceDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        deviceDaoConfig = daoConfigMap.get(DeviceDao.class).clone();
        deviceDaoConfig.initIdentityScope(type);

        mDeviceDaoConfig = daoConfigMap.get(MDeviceDao.class).clone();
        mDeviceDaoConfig.initIdentityScope(type);

        deviceDao = new DeviceDao(deviceDaoConfig, this);
        mDeviceDao = new MDeviceDao(mDeviceDaoConfig, this);

        registerDao(Device.class, deviceDao);
        registerDao(MDevice.class, mDeviceDao);
    }
    
    public void clear() {
        deviceDaoConfig.clearIdentityScope();
        mDeviceDaoConfig.clearIdentityScope();
    }

    public DeviceDao getDeviceDao() {
        return deviceDao;
    }

    public MDeviceDao getMDeviceDao() {
        return mDeviceDao;
    }

}
