package ru.yugsys.vvvresearch.lconfig.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import ru.yugsys.vvvresearch.lconfig.model.Dev_Data;

import ru.yugsys.vvvresearch.lconfig.model.Dev_DataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dev_DataDaoConfig;

    private final Dev_DataDao dev_DataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dev_DataDaoConfig = daoConfigMap.get(Dev_DataDao.class).clone();
        dev_DataDaoConfig.initIdentityScope(type);

        dev_DataDao = new Dev_DataDao(dev_DataDaoConfig, this);

        registerDao(Dev_Data.class, dev_DataDao);
    }
    
    public void clear() {
        dev_DataDaoConfig.clearIdentityScope();
    }

    public Dev_DataDao getDev_DataDao() {
        return dev_DataDao;
    }

}
